language: node_js
node_js:
  - '14'
jobs:
  include:
    - stage: tests
      name: Build
      script: npm run build
    - name: Unit Tests
      script: npm run test:unit
      services:
        - postgresql
    - name: Lint
      script: npm run test:lint
    - name: Prettier
      script: npm run prettier:check