language: node_js
node_js:
  - '14'
jobs:
  include:
    - stage: Tests
      name: Build
      script: npm run build
    - name: Lint
      script: npm run lint
    - name: Format
      script: npm run format:check
    - name: Unit Tests
      script: npm run test:cov
    - name: E2E Tests
      script: npm run test:e2e
      services:
        - postgresql